## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np
print("Give me a number")
N=int(input())
pochti=[g for g in range(N-1,-1,-1)]
V=np.array(pochti)   
V

Give me a number


 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
print("Give me a number")
N=int(input())
pochti=[g for g in range(N-1,-1,-1)]
V=np.diag(pochti) 
print(V)
#Another method
V0=np.diag(np.arange(N-1,-1,-1))
#Solution 1
S1=sum(np.diag(V).tolist())
print("Solution 1: The sum of diagonal's elements is ",S1)
#Solution 2 
S2=sum([i for i in V[(V>0)]])
print("Solution 2: The sum of diagonal's elements is ",S2)
#Solution 3 
S3=sum([V[i,i] for i in range(N-1,-1,-1)])
print("Solution 3: The sum of diagonal's elements is ",S3)
#Solution 4 (the easiest one)
S4=np.sum(np.diag(V))
print("Solution 4: The sum of diagonal's elements is ",S4)


Give me a number


 11


[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Solution 1: The sum of diagonal's elements is  55
Solution 2: The sum of diagonal's elements is  55
Solution 3: The sum of diagonal's elements is  55
Solution 4: The sum of diagonal's elements is  55


## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [3]:
from numpy import linalg
A = np.matrix([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
B = np.matrix([[4], [12], [-3]])
XYZ = np.around(np.linalg.solve(A, B),decimals=1)
print(XYZ)
#OR
O=linalg.inv(A)
XYZ1=np.around(O*B,decimals=1)
print(XYZ1)
print("x=",round(XYZ[0,0],1),", y=",round(XYZ[1,0],1),", z=",round(XYZ[2,0],1))

[[ 0.5]
 [ 3.8]
 [-5.6]]
[[ 0.5]
 [ 3.8]
 [-5.6]]
x= 0.5 , y= 3.8 , z= -5.6


## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [4]:
#If vector looks like (x,y,z):
from random import randint

a=input("Vector a:")
b=input("Vector b:")
i=np.array([int(a1) for a1 in a.replace("(","").replace(")","").split(",")])
j=np.array([int(b1) for b1 in b.replace("(","").replace(")","").split(",")])
for n,e in enumerate(i):
    i[n]=randint(-100,100)
for n,e in enumerate(j):
    j[n]=randint(-100,100)

v1=tuple(i)#making it looks like a vector
v2=tuple(j)
print("Vector a after replacement",v1,"\nVector b after replacement",v2)
DP=np.dot(i,j)
print("Dot product of vectors a and b is",DP)



Vector a: (1,2,3)
Vector b: (1,2,3)


Vector a after replacement (-50, -98, 57) 
Vector b after replacement (-2, -79, 61)
Dot product of vectors a and b is 11319
